import { PrismaClient } from '../prisma/generated/client/index.js';

const prisma = new PrismaClient();

// This object defines the structure of a full census file from Ease.
// It maps the column header in the CSV to our internal database field name.
const fullCensusTemplate = {
  templateKey: 'ease-full-census',
  name: 'Ease Full Employee Census',
  description: 'The standard, comprehensive employee and dependent census file generated by Ease.',
  fields: [
    { columnName: 'EID', mapsToField: 'eid', isRequired: true },
    { columnName: 'First Name', mapsToField: 'firstName', isRequired: true },
    { columnName: 'Last Name', mapsToField: 'lastName', isRequired: true },
    { columnName: 'Middle Name', mapsToField: 'middleName', isRequired: false },
    { columnName: 'Relationship', mapsToField: 'relationship', isRequired: true },
    { columnName: 'SSN', mapsToField: 'ssn', isRequired: false },
    { columnName: 'Birth Date', mapsToField: 'birthDate', isRequired: false },
    { columnName: 'Sex', mapsToField: 'gender', isRequired: false },
    { columnName: 'Marital Status', mapsToField: 'maritalStatus', isRequired: false },
    { columnName: 'Email', mapsToField: 'email', isRequired: false },
    { columnName: 'Personal Email', mapsToField: 'personalEmail', isRequired: false },
    { columnName: 'Address 1', mapsToField: 'address1', isRequired: false },
    { columnName: 'Address 2', mapsToField: 'address2', isRequired: false },
    { columnName: 'City', mapsToField: 'city', isRequired: false },
    { columnName: 'State', mapsToField: 'state', isRequired: false },
    { columnName: 'Zip Code', mapsToField: 'zipCode', isRequired: false },
    { columnName: 'County', mapsToField: 'county', isRequired: false },
    { columnName: 'Personal Phone', mapsToField: 'personalPhone', isRequired: false },
    { columnName: 'Work Phone', mapsToField: 'workPhone', isRequired: false },
    { columnName: 'Mobile Phone', mapsToField: 'mobilePhone', isRequired: false },
    { columnName: 'Hire Date', mapsToField: 'hireDate', isRequired: false },
    { columnName: 'Termination Date', mapsToField: 'terminationDate', isRequired: false },
    { columnName: 'Employment Type', mapsToField: 'employmentType', isRequired: false },
    { columnName: 'Status', mapsToField: 'status', isRequired: false },
    { columnName: 'Job Title', mapsToField: 'jobTitle', isRequired: false },
  ]
};

async function main() {
  console.log('Seeding census templates into the database...');

  await prisma.censusTemplate.upsert({
    where: { templateKey: fullCensusTemplate.templateKey },
    update: {},
    create: {
      templateKey: fullCensusTemplate.templateKey,
      name: fullCensusTemplate.name,
      description: fullCensusTemplate.description,
      fields: {
        create: fullCensusTemplate.fields,
      },
    },
  });

  console.log('✅ Census template seeding complete.');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });